### ISSUE TITLE
Cannot find VMware NSX-T Container Plug-in version 3.0.2.2

### ISSUE THREAD

**Issue by labrown** [pivotal-cf/pivnet-resource#135]
Hi,  Vmware recently released version 3.0.2.2 of the VMware NSX-T Container Plugin-in and I cannot make my pivnet-resource based concourse pipeline discover that version at all.  It sees the 3.0.2 release but none of the version regexes I've tried locate 3.0.2.2.

I tried the following product_version regexes:
^.+$
^3\.0\..+$
3\.0\.2\.2
and even tried taking the product_version out completely.  The resource stubbornly continues to return the 3.0.2 version.

Does pivnet-resource not like a 4 segment semver?

**Comment by xtreme-conor-nosal** [comment]
The resource uses https://github.com/blang/semver to parse semver, and pads .0 if there's < 3 parts (https://github.com/pivotal-cf/pivnet-resource/blob/master/semver/semver.go). I don't believe 4 segments is valid semver (https://semver.org/).

When sorting by semver, invalid versions are excluded. You could try sorting by `last_updated` instead of `semver`.

**Comment by xtreme-conor-nosal** [comment]
Releases are managed by the individual product teams. When standard semver isn't consistently used it can cause difficulties.
