### ISSUE TITLE
optional delayed dates in check resource

### ISSUE THREAD

**Issue by ywei2017** [pivotal-cf/pivnet-resource#143]
We have pipelines that daily download the latest releases, which trigger other pipelines to install the release through the environments

We have had a several times, the latest release actually cause issues. After discussion with supports, the idea of "why not wait a little bit on new releases" came up.

But how can we do it? We can run the pipeline less often, but that doesn't resolve the issue.

One thing we thought of is to add an optional flag like "minimum_release_days", so it only returns a release if that release has been out for the mininum number of days.

Thoughts? 

I will be happy to submit a PR if that makes it easier.

**Comment by pivotal-so** [comment]
Hey there @ywei2017 , I appreciate your patience in awaiting a response.

We've since taken this context and created a ticket to manage the progress of this feature request. I cannot comment on the design and possible solution of `minimum_release_days` but certainly appreciate the effort and thought in constructing this issue. Even more so in the case of submitting a PR yourself 😃 

Myself and others on the team will provide updates as this work is picked up.

**Comment by ywei2017** [comment]
Closing the issue. I am transitioning to a new role and won't be able to work/test on it.
