### ISSUE TITLE
Concourse resource cache using old versions of PivNet resources causes errors

### ISSUE THREAD

**Issue by freynca** [pivotal-cf/pivnet-resource#43]
When running a pipeline that fetches PivNet releases using the PivNet resource (https://github.com/pivotal-cf/pivnet-resource), attempting to fetch an older version of a resource errors out with:
```
Exiting with error: provided fingerprint: '...' does not match actual fingerprint (from pivnet): '...' - pivnet does not support downloading old versions of a release
```

PivNet does not allow older versions of a release to be downloaded. Concourse resource caching does not fit this model, unless all jobs in a given pipeline are pinned to the same worker.

Example pipeline to reproduce:
[job: pivnet-trigger] trigger when a pivnet resource changes
[other jobs that take time] passing the pivnet resource along
[job that reads the pivnet resource]

If a new version of a resource (with the same semver) appears during the execution of the 2nd step above, and the jobs run on different workers, the 3rd step would error out.

**Comment by robdimsdale** [comment]
@freynca thanks for the feedback. This feature was added a while back, but was recently expanded to differentiate releases more accurately - it now updates the version whenever the release is saved. If the `pivnet-resource` has been working fine for you up until this point, I would suspect that's the change.

Getting into the issue, it's a tricky one. If this feature were disabled, what you would observe is the same "version" resulting in different releases on disk. Anything (except the version) could be different. For example, the product files could have been updated. This might mean that part of your CI runs with one file, and part with another.

Failing fast if the `updated_at` doesn't match was introduced to avoid this issue, however it comes  with exactly the issue you observe - that Pivotal Network cannot actually give you old versions of the tile. Even if it could, if tile authors are creating tiles that quickly your pipeline would be stale as soon as it was complete. This may or may not be an issue; it depends on the changes to the product.

I think the right solution here is that tile authors don't expose them to downstream teams until they're ready - for example by using `user_groups` and avoiding making changes to releases after this point. This would avoid the thrash you're seeing, without sacrificing the safety of running a stale version, and it also avoids requiring pivnet to support old versions (which seems like a lot of effort for little gain outside of this issue).

**Comment by robdimsdale** [comment]
@crawsible do you have any thoughts?

**Comment by crawsible** [comment]
Hi @freynca, Pivnet PM here. I agree that product teams should do their best to keep new release models stable. I suspect product teams are more cavalier about changing release metadata before the release is made available to All Users, so perhaps filtering releases based on their availability makes sense for your use-case? Are you consuming GA releases or prerelease builds?

I don't see an obvious Pivnet-side way around the bigger issue though. As @robdimsdale mentioned, releases generally change for a reason; a product team may have updated its dependencies list, added a product file to it, or changed its designated release type (from Maintenance to Security, for instance). In other words, it's probably a good thing that you can't get at that previous Pivnet release's construction.

I don't see a world where releases are likely to ever truly be immutable; even in the most restrictive (and extremely far-flung) case where all release data are immutable, I can't see us preventing product teams from pulling releases down in response to security concerns or game-breaking bugs. Removing a release from Pivnet is functionally equivalent to updating a release and making the `pivnet-resource`'s previous `<version>#<timestamp>` fingerprint for that release inaccessible -- both pull the rug out from under the `pivnet-resource`.

If your pipeline triggers due to a configured resource receiving a new release, and then a product admin changes the metadata or files of that same release, I would expect:

1. future jobs that rely on the previous release version that passed the first job will fail
2. the initial job will be triggered a second time by the update to the release
3. future jobs will trigger on the release with the later timestamp and succeed

Is this a correct description of the current behavior? If not, what am I missing?

**Comment by freynca** [comment]
Thanks for the quick response @crawsible and @robdimsdale

We want to encourage product teams to publish tiles more frequently, and we don't have an issue with them updating a specific release after it has been uploaded (so long as the update itself is timestamped). We consume both GA and pre-GA releases. 

Our issue is captured by the # 1 item in @crawsible's response - subsequent jobs in the pipeline fail, since they are meant to consume a release that triggered the pipeline to begin with, and that release becomes outdated during pipeline execution.

While # 2 and # 3 are correct, the scale at which we operate causes this failure to occur frequently. We currently consume 9 PivNet releases, and that number will only grow. These failure cases cause significant delays and force us to re-execute a pipeline that takes 6+ hours to run.

Perhaps there could be a separate class of PivNet consumer, per-account or per-API-key, which is focused on automation. It would differ from a regular consumer by having access to artifacts from older timestamps of releases, even if the release itself has since been updated.

**Comment by robdimsdale** [comment]
I will let @crawsible speak to the implications of implementing historical versions on pivnet, but from my understanding this would be a non-trivial engineering effort and the only benefit would be to this issue.

What if the the `get` took an optional parameter `ignore_fingerprint`, defaulting to `false`, which would allow you to download the latest version of a release irrespective of the fingerprint (i.e. the timestamp).

This seems like a bad idea to me because i see a situation where we incorrectly validated a bad tile, for example the first step validates the contents of the product files but then the next step uploads a different product file.

You know your own pipeline more than I do,so if this is something you think you would find helpful let me know and I'll add it.

**Comment by crawsible** [comment]
@freynca I share @robdimsdale's concern with master pipeline signing off on a release that's different from the one that actually went through the pipeline. Changes as significant as replacing the associated `.pivotal` file can and do occur after a release has been created on Pivnet.

Can we jump on a quick call at some point this week, Felix? I'm in NY, so I'm on your schedule. I'd like to better understand master pipeline's use case and what statement the pipeline is making when a release passes through it successfully.

**Comment by pronoiac** [comment]
As a heads-up, this issue is also impacting the Pivotal Cloudops Hosted team.

**Comment by robdimsdale** [comment]
Thanks for the feedback all.

PivNet is going to implement a `product_files_last_updated_at` field, which we will then optionally allow pivnet-resource users to use instead of the more general `last_updated` at.

This will be an optional feature, configured in the resource `source` config, probably called `fingerprint_components`, and I imagine it looks something like the following:

```
- name: product-i-care-about
  type: pivnet
  source:
    api_token: my-api-token
    product_slug: some-product-slug
    fingerprint_components:
    - product-files
```

This allows future extensibility, for example, if we find that we also need to support other metadata like dependencies or upgrade paths we can add them to the array.

An empty value for `fingerprint-components` will fall-back to the existing `last_updated` which considers all changes to the release. Any value other than `product-files` will fail-fast.

@freynca @pronoiac how does this sound to you?

**Comment by robdimsdale** [comment]
I'm not seeing any objections to my proposal above, so we will move forward with that plan. We will keep this issue open until this is complete.

**Comment by freynca** [comment]
We re-worked our pipeline structure to consume Pivnet resources in a just-in-time manner, bypassing this issue altogether. Thanks for your assistance.

**Comment by robdimsdale** [comment]
Ok thanks for the update @freynca. Out of curiosity, can you expand on what you mean by "just-in-time" resource consumption?

**Comment by freynca** [comment]
@robdimsdale In the old implementation, we were tracking Pivnet resources from the beginning of the pipeline, passing them along until they were consumed in an appropriate job (typically hours after they first entered the pipeline). This interval caused issues when a release was pulled/updated in the meantime. The new implementation still triggers the pipeline when new resources show up, but we no longer pass them along; instead, the resource on the consuming job is directly attached to that job. This required adjusting how we track tile/add-on versions, but freed us from this Pivnet issue.

**Comment by crawsible** [comment]
@freynca glad you managed to work around the issue. Would you mind my asking when your team settled on this readjustment?

**Comment by freynca** [comment]
@crawsible About 3 weeks ago.

**Comment by bonzofenix** [comment]
@robdimsdale @crawsible we currently have 4 environments of at least 2 foundations each. New tiles sometime take up to a week to propagate through all our environments. We often run into this issue. We might end up vendoring dependencies. I hope we do not get to this and we can get to use the `product_files_last_updated_at` feature. Has there been any progress on this so far. Also form a security/audit point of view we need tiles SHA to match in all environments, which if we understand correctly this feature would not solve this. We might end up with different SHA on all environments while having the same semver in all of them.

@bonzofenix && @henrys24
