### ISSUE TITLE
failed to download stemcell 3263.13 due to fingerprint mismatch

### ISSUE THREAD

**Issue by syslxg** [pivotal-cf/pivnet-resource#58]
```
2017/01/11 18:21:38 PivNet Resource version: 0.29.0
2017/01/11 18:21:38 Creating download directory: /tmp/build/get
2017/01/11 18:21:38 Getting release for product slug: 'stemcells' and product version: '3263.13'
ERROR: provided fingerprint: '2016-12-14T03:13:59.009Z' does not match actual fingerprint (from pivnet): '2016-12-16T16:25:28.399Z' - pivnet does not support downloading old versions of a release
```

it seems the fingerprint changed on pivnet. But can we make this resource not check the fingerprint?

**Comment by robdimsdale** [comment]
@syslxg this has come up before - see https://github.com/pivotal-cf/pivnet-resource/issues/43.

We ended up not needing to implement this feature, because it's usually an issue with the way resources are passed through a pipeline. Are you passing the stemcell through multiple jobs? Also, the stemcells don't change often, so how often are you seeing this?

**Comment by bonzofenix** [comment]
We fixed this issue by getting refreshing older references of the resource that we wanted through `check-resource`. e.g.:

```
fly check-resource -r PIPELINE_NAME/stemcell -f product_version:3263.8#2016-12-16T16:25:30.148Z 
```
