### ISSUE TITLE
"pivnet does not support downloading old versions of a release"

### ISSUE THREAD

**Issue by benmoss** [pivotal-cf/pivnet-resource#69]
Here's the scenario we encounter on a semi-regular basis:

- We are building against Foo 1.1
- PivNet owners of Foo release 2.0 and update something that causes the fingerprint of 1.1 to change
- We don't want to update to 2.0, so we pause that version in our resource list
- Builds all perma-fail until we do some hackery because we never see the new fingerprint for 1.1

Are we doing something wrong?

**Comment by dannysullivan** [comment]
Hi Ben,

My understanding of this issue is this: 
1. Concourse resources expect to always be able to access a particular version of a resource
1. Pivnet doesn't keep records of previous versions of releases
1. When a release is updated in any way (including when associated product files are updated), the concourse "version" of the release changes.
1. The Pivnet resource notices that the release version it's looking for is no longer available and will never be available again and gives up.

Is "Foo" a consistent Pivnet product?  It's possible we're updated releases too eagerly in some circumstances, which is why version 2.0 would update 1.1.

cc: @jimbosity, @crawsible

**Comment by benmoss** [comment]
I'm not sure what makes version 1.1 change. I'd always thought the product owner was both shipping 2.0 and updating some metadata in 1.1 that causes the resource to consider it a new version.

This is a screenshot of our actual scenario, you can see that the "new" 0.14.1 came out 4ms before 0.15.0, so I'm not really sure what happened. I think the resource is using the `updated_at` field exposed on release versions, maybe this is being updated when a new version is released?

![screen shot 2017-03-15 at 3 05 30 pm](https://cloud.githubusercontent.com/assets/239754/23966188/de56d86a-0990-11e7-9f71-af0d4054465d.png)

**Comment by benmoss** [comment]
Oh and the fix we had to do to get the new 0.14.1 to show up was to reconfigure the resource to have a `product_version` param that only matches the 0.14 series

**Comment by robdimsdale** [comment]
I think @benmoss's description of the situation is accurate - @youreddy ran into this too (with the same product, judging by the versions).

The pivnet resource uses the `update_at` as a way of determining if a given version has changed (product file, metadata etc), but pivnet doesn't support fetching previous versions of a release, so it doesn't play nicely with concourse, which expects old versions of a release to be gettable.

Usually this isn't a problem, because the `check` and `get` steps are close enough together in a pipeline that the download matches the most-recent `updated_at`.

In this case it appears that the upstream product updated both `0.14.1` and `0.15.0` at the same time, and so the pivnet resource only discovered the most recent, and the previous `0.14.1` was stale. This can be fixed by the upstream product not making these changes (cc @avade) or by the consumes pinning the version (as @benmoss mentioned).

**Comment by robdimsdale** [comment]
https://github.com/pivotal-cf/pivnet-resource/issues/43 has more context on this issue

**Comment by bonzofenix** [comment]
At Allstate, we run into this problem often. We have 4 different environments with multiple foundations each. sometimes it takes us a couple of days to pipe these versions through the different environments.
The `depends_on` feature of Concourse, in this case, does not work for us and we usually need to go back and re-pipe the same version through all the lower environments.

**Comment by dannysullivan** [comment]
The latest version of pivnet-resource (https://github.com/pivotal-cf/pivnet-resource/releases/tag/v0.30.7) only detects new versions when software-type product files are changed on a release.  I'm closing this issue, but please let us know if this problem resurfaces.
